### ISSUE TITLE
segfault on Android 6

### ISSUE THREAD

**Issue by eadmaster** [termux/termux-exec#12]
I've just installed the latest termux from the play store and it is working  fine on my Android 6 smartphone 

Btw the preinstalled termux-exec package does not seem to work:
the `LD_PRELOAD` envvar is not set at login and if i set it manually i get segfauls  when i try to run a shellscript...

**Comment by ghost** [comment]
Unfortunately, on some devices termux-exec is broken. Likely due to bug in /system/lib/libc.so.

Login script does checks to prevent usage of termux-exec on these devices: see [termux-packages/packages/termux-exec/build.sh](https://github.com/termux/termux-packages/blob/master/packages/termux-tools/login#L20).
That's why LD_PRELOAD is unset.
